config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end
  namespace :todo_list do
    resources :todo_items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, -> do
    where(completed: true)
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items

  def total_items
    @total_items ||= todo_items.count
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def percent_complete
    return 0 if total_items == 0
    (100 * completed_items.to_f / total_items).round(1) 
  end

  def status
    case percent_complete.to_i
    when 0
      'not started'
    when 100
      'complete'
    else
      'in progress'
    end
  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'info'
    else
      'in primary'
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/1
  def show
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.todo_list)
    else
      render action: 'new'
    end
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update_attributes(todo_item_params)
      redirect_to([@todo_item.todo_list, @todo_item], notice: 'Todo item was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    redirect_to todo_list_todo_items_url(@todo_list)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :completed_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: "Todo list was successfully created." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: "Todo list was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To do App Version 01</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-light'>
    <div class ="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          <div class="card mt-5">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_with(model: [@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :completed_at %><br />
    <%= f.datetime_select :completed_at %>
  </div>
  <div class="field">
    <%= f.label :todo_list %><br />
    <%= f.text_field :todo_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_item.todo_list, @todo_item] %> |
<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/index.html.erb
<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Completed</th>
    <th>Completed at</th>
    <th>Todo list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.description %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.completed_at %></td>
    <td><%= todo_item.todo_list %></td>
    <td><%= link_to 'Show', [todo_item.todo_list, todo_item] %></td>
    <td><%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
    <td><%= link_to 'Destroy', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo item', new_todo_list_todo_item_path(params[:todo_list_id]) %>

app/views/todo_items/new.html.erb
<h1>New todo_item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @todo_item.description %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo_item.completed %>
</p>

<p>
  <b>Completed at:</b>
  <%= @todo_item.completed_at %>
</p>

<p>
  <b>Todo list:</b>
  <%= @todo_item.todo_list %>
</p>


<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item) %> |
<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<div class="card-header d-flex justify-content-between">
  <h5 class='m-0 text-dark'>
    To do Lists
  </h5>
  <%= link_to 'New To Do List', new_todo_list_path %>
</div>

<div class="card-body">
  <ul class="list-group">
    <% @todo_lists.each do |todo_list| %>
      <%= link_to todo_list, class: 'text-decoration-none' do %>
        <li class="list-group-item d-flex justify-content-between">
          <div>
            <h6 class='m-0 text-dark'>
              <b><%= todo_list.title %></b>
              <span class="badge badge-<%= todo_list.badge_color %>"><%= todo_list.status %> </span>
            </h6>
            <p class='text-secondary m-0'>
              <small>
              <%= todo_list.percent_complete %>% complete  
              (<%= todo_list.completed_items %>/<%= todo_list.total_items %>)
              </small>
            </p>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<div class="card-header">

  <div class="row">
    <div class="col-1">
      <%= link_to todo_lists_path, class: 'btn btn-dark' do %>
        <i class="fas fa-arrow-circle-left"></i>      
      <% end %>
    </div>

    <div class="col-11">
      <div class="d-flex justify-content-between">
        <div>
          <h5 class='m-0'>
            <b><%= @todo_list.title %></b>
            <span class="badge badge-<%= @todo_list.badge_color %>"><%= @todo_list.status %> </span>
          </h5>
          <p class='text-secondary m-0'>
            <small>
              <%= @todo_list.percent_complete %>% complete  
              (<%= @todo_list.completed_items %>/<%= @todo_list.total_items %>)
            </small>
          </p>
        </div>
        <div>
          <%= link_to 'edit', edit_todo_list_path(@todo_list), class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

  <div class="progress">
    <div class="progress-bar bg-info" role="progressbar" style="width: <%= @todo_list.percent_complete %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
  </div>

<div class="card-body">
  <%= form_for([@todo_list, @todo_item]) do |f| %>
    <div class="input-group mb-4">
      <%= f.text_field :description, class: 'form-control', placeholder: 'add a task' %>
      <div class="input-group-append">
        <%= f.submit "add", class: "btn btn-primary input-group-btn" %>
      </div>
    </div>
  <% end %>

  <ul class="list-group">
    <% @todo_list.todo_items.each do |todo_item| %>
      <% if !todo_item.completed? %>

        <li class="list-group-item bg-light">
          <div class="d-flex justify-content-between">
            <span>
              <%= todo_item.description %>
            </span>
            <%= link_to '#', class: "btn btn-info", data: { reflex: 
                'click->TodoItem#mark_complete', id: todo_item.id } do %>
              <i class='fas fa-check'></i>
            <% end %>
          </div>
        </li>
      <% else %>
      <li class="list-group-item bg-light">
          <div class="d-flex justify-content-between">
            <span class="text-muted">
              <em><%= todo_item.description %></em>
            </span>
            <%= link_to '#', class: "btn btn-dark", data: { reflex: 
                'click->TodoItem#mark_incomplete', id: todo_item.id } do %>
              <i class='fas fa-times'></i>
      <% end %>
    <% end %>
  </ul>
  <% end %>
</div>